#!/bin/bash

echo "					"
echo "help- display help messages"
echo "clear- clears the screen"
echo "tool- displays info about the tool"
echo "info- displays computer and network info"
echo "+----------------------------+"
echo "speak- text to speech"
echo "ping- ping a host"
echo "banner- print a new banner"
echo "joke- tell a joke"
echo "quote- print a quote"
echo "contact- contact me"
echo "+----------------------------+"
echo "website- enter a website and get its ip"
echo "clone- clone a websites source "
echo "whois- whois a website"
echo "web- extract info from a website"
echo "siteexists- check if a site exists"
echo "google- find google results for a query"
echo "+----------------------------+"
echo "ip- geolocate an ip"
echo "+----------------------------+"
echo "xss- simple check for a xss vulnerability"
echo "sql- basic check for a sql vulnerability"
echo "admin- scan a website for its admin panel"
echo "+----------------------------+"
echo "email- bomb an email address"
echo "spoof email- spoof an email address"
echo "anonymous- send an anonymous email"
echo "sms- spam text messages "
echo "twitter- check the details of a twitter account"
echo "+----------------------------+"
echo "craft- generate useful scripts "
echo "qr- generate a qr code"
echo "zip- crack a password-protected zip file"
echo "+----------------------------+"
echo "encode base64- text to base64"
echo "decode base64- base64 to text"
echo "encode hex- text to hex"
echo "decode hex- hex to text"
echo "+----------------------------+"

cd Trity-1
trity
